const PERMISSION = Object.freeze({
  KPI_DASHBOARD_VIEW: "kpi.dashboard.view",
  KPI_METRIC_MANAGE: "kpi.metric.manage",
  KPI_YEAR_PLAN_ASSIGN: "kpi.year_plan.assign",
  KPI_YEAR_PLAN_ALLOCATE: "kpi.year_plan.allocate",
  KPI_ASSIGNMENT_MANAGE: "kpi.assignment.manage",
  KPI_TIER_CONFIG: "kpi.tier.config",
  KPI_REPORT_SUBMIT: "kpi.report.submit",
  KPI_MONTHEND_CLOSE: "kpi.monthend.close",
  HRM_REQUEST_VIEW_ALL: "hrm.request.view_all",
  HRM_REQUEST_REVIEW_ALL: "hrm.request.review_all",
  HRM_REQUEST_REVIEW: "hrm.request.review",
  HRM_ATTENDANCE_IMPORT: "hrm.attendance.import",
  HRM_ATTENDANCE_EDIT: "hrm.attendance.edit",
  HRM_EMPLOYEE_VIEW: "hrm.employee.view",
  HRM_EMPLOYEE_EDIT: "hrm.employee.edit",
  HRM_MENU_ATTENDANCE_SETTINGS: "hrm.menu.attendance_settings",
  HRM_MENU_HR_MANAGEMENT: "hrm.menu.hr_management",
  HRM_MENU_DEPARTMENT: "hrm.menu.department",
  HRM_MENU_BRANCH: "hrm.menu.branch",
  HRM_MENU_WORK_UNIT: "hrm.menu.work_unit",
  HRM_MENU_EVENTS: "hrm.menu.events",
  HRM_MENU_DOCUMENTS: "hrm.menu.documents",
  HRM_MENU_POSITIONS: "hrm.menu.positions",
  HRM_MENU_ATTENDANCE_MAPPING: "hrm.menu.attendance_mapping",
  HRM_MENU_PERMISSIONS: "hrm.menu.permissions",
  HRM_MENU_PERMISSIONS_RBAC: "hrm.menu.permissions_rbac",
  HRM_MENU_EMPLOYEE: "hrm.menu.employee",
  HRM_MENU_LABOR_CONTRACT: "hrm.menu.labor_contract",
  HRM_MENU_RECRUITMENT: "hrm.menu.recruitment",
  HRM_MENU_RECRUITMENT_PLAN: "hrm.menu.recruitment_plan",
  HRM_MENU_CANDIDATE_PROFILE: "hrm.menu.candidate_profile",
  HRM_MENU_TRAINING: "hrm.menu.training",
  HRM_MENU_TRAINING_PLAN: "hrm.menu.training_plan",
  HRM_MENU_TRAINEE_MANAGEMENT: "hrm.menu.trainee_management",
  HRM_MENU_REGULATION_DOCUMENT: "hrm.menu.regulation_document",
  HRM_MENU_REGULATION: "hrm.menu.regulation",
  HRM_MENU_DOCUMENT_MANAGEMENT: "hrm.menu.document_management",
  HRM_MENU_PERFORMANCE: "hrm.menu.performance",
  HRM_MENU_KPI: "hrm.menu.kpi",
  HRM_MENU_TASK_REPORT: "hrm.menu.task_report",
  HRM_MENU_ASSET_MANAGEMENT: "hrm.menu.asset_management",
  HRM_MENU_ASSET_LIST: "hrm.menu.asset_list",
  HRM_MENU_ASSET_REQUEST: "hrm.menu.asset_request",
  HRM_MENU_SYSTEM_SETTINGS: "hrm.menu.system_settings",
  FOLDER_MENU_DOCUMENTS: "folder.menu.documents",
  FOLDER_SHARED_VIEW: "folder.shared.view",
  FOLDER_SHARED_DOWNLOAD: "folder.shared.download",
  FOLDER_SHARED_UPLOAD: "folder.shared.upload",
  FOLDER_SHARED_PUSH: "folder.shared.push",
  FOLDER_SHARED_DELETE_FILE: "folder.shared.delete_file",
  FOLDER_SHARED_CREATE: "folder.shared.create",
  FOLDER_SHARED_MANAGE: "folder.shared.manage"
});

const PERMISSION_VALUES = Object.values(PERMISSION);

module.exports = { PERMISSION, PERMISSION_VALUES };
